### ISSUE TITLE
tomcat9开发环境部署后打印日志乱码

### ISSUE THREAD

**Issue by lanxxz** [lagouedu/tomcat-source-code-analysis#249]
1、tomcat9开发环境部署后打印日志乱码
2、org.apache.catalina.LifecycleException: åè®®å¤çå¨å¯å¨å¤±è´¥
		at org.apache.catalina.connector.Connector.startInternal(Connector.java:1067)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:438)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
	Caused by: java.lang.IllegalArgumentException: AJPè¿æ¥å¨éç½®secretRequired="true",ä½æ¯å±æ§secretç¡®å®ç©ºæèç©ºå­ç¬¦ä¸²ï¼è¿æ ·çç»åæ¯æ æçã
		at org.apache.coyote.ajp.AbstractAjpProtocol.start(AbstractAjpProtocol.java:270)
		at org.apache.catalina.connector.Connector.startInternal(Connector.java:1064)
		... 12 more
这是什么情况？
有朋友知道怎么解决的么？

**Comment by xuwei0407** [comment]
日志配置文件，logging.properties的问题，目前还不知道怎么解决。

**Comment by lanxxz** [comment]
问题已解决，贴上两个地址
https://www.cnblogs.com/hixiaowei/p/12380777.html 异常问题
https://www.cnblogs.com/davidwang456/p/11224923.html  乱码问题
